/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as MainShopRouteImport } from './routes/_main/shop'
import { Route as MainLibraryRouteImport } from './routes/_main/library'
import { Route as MainDashboardRouteImport } from './routes/_main/dashboard'
import { Route as MainAppsIndexRouteImport } from './routes/_main/apps/index'
import { Route as MainAppsAppIdRouteImport } from './routes/_main/apps/$appId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const MainShopRoute = MainShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainLibraryRoute = MainLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainDashboardRoute = MainDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAppsIndexRoute = MainAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAppsAppIdRoute = MainAppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => MainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof MainDashboardRoute
  '/library': typeof MainLibraryRoute
  '/shop': typeof MainShopRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/': typeof SettingsIndexRoute
  '/apps/$appId': typeof MainAppsAppIdRoute
  '/apps': typeof MainAppsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof MainDashboardRoute
  '/library': typeof MainLibraryRoute
  '/shop': typeof MainShopRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings': typeof SettingsIndexRoute
  '/apps/$appId': typeof MainAppsAppIdRoute
  '/apps': typeof MainAppsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_main': typeof MainRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_main/dashboard': typeof MainDashboardRoute
  '/_main/library': typeof MainLibraryRoute
  '/_main/shop': typeof MainShopRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/': typeof SettingsIndexRoute
  '/_main/apps/$appId': typeof MainAppsAppIdRoute
  '/_main/apps/': typeof MainAppsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/onboarding'
    | '/dashboard'
    | '/library'
    | '/shop'
    | '/settings/profile'
    | '/settings/'
    | '/apps/$appId'
    | '/apps'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/dashboard'
    | '/library'
    | '/shop'
    | '/settings/profile'
    | '/settings'
    | '/apps/$appId'
    | '/apps'
  id:
    | '__root__'
    | '/'
    | '/_main'
    | '/settings'
    | '/onboarding'
    | '/_main/dashboard'
    | '/_main/library'
    | '/_main/shop'
    | '/settings/profile'
    | '/settings/'
    | '/_main/apps/$appId'
    | '/_main/apps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRouteRoute: typeof MainRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/_main/shop': {
      id: '/_main/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof MainShopRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/library': {
      id: '/_main/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof MainLibraryRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/dashboard': {
      id: '/_main/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof MainDashboardRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/apps/': {
      id: '/_main/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof MainAppsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/apps/$appId': {
      id: '/_main/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof MainAppsAppIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface MainRouteRouteChildren {
  MainDashboardRoute: typeof MainDashboardRoute
  MainLibraryRoute: typeof MainLibraryRoute
  MainShopRoute: typeof MainShopRoute
  MainAppsAppIdRoute: typeof MainAppsAppIdRoute
  MainAppsIndexRoute: typeof MainAppsIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainDashboardRoute: MainDashboardRoute,
  MainLibraryRoute: MainLibraryRoute,
  MainShopRoute: MainShopRoute,
  MainAppsAppIdRoute: MainAppsAppIdRoute,
  MainAppsIndexRoute: MainAppsIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRouteRoute: MainRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
